baseURL: "https://matusnovak.com/"
languageCode: "en-us"
title: "Matus Novak"
theme: "config"
defaultcontentlanguage: "en-US"
uglyURLs: true

deployment:
  targets:
    name: "aws"
    URL: "s3://matusnovak.com?region=eu-west-1"
    cloudFrontDistributionID: "E1WO2HFAIAXKQ8"
