baseURL = "https://matusnovak.com/"
languageCode = "en-us"
title = "Matus Novak"
theme = "hugo-coder"
defaultcontentlanguage = "en-US"

paginate = 20
canonifyurls = true

pygmentsstyle = "bw"
pygmentscodefences = true
pygmentscodefencesguesssyntax = true

disqusShortname = "yourdiscussshortname"

[params]
    author = "Matus Novak"
    info = "Software Developer"
    description = "Matus Novak's personal website"
    keywords = "blog,developer,personal"
    avatarurl = "avatar.jpg"

    footercontent = ""

    hidecredits = false
    hidecopyright = false

    rtl = false

    math = true
    custom_css = ["css/custom.css"]

# Social links
[[params.social]]
    name = "Github"
    icon = "fab fa-github fa-2x"
    weight = 1
    url = "https://github.com/matusnovak/"
[[params.social]]
    name = "LinkedIn"
    icon = "fab fa-linkedin"
    weight = 2
    url = "https://www.linkedin.com/in/matus-novak-57153218a/"
[[params.social]]
    name = "Email"
    icon = "fa fa-envelope fa-2x"
    weight = 3
    url = "mailto:email@matusnovak.com"
[[params.social]]
    name = "GPG"
    icon = "fa fa-lock fa-2x"
    weight = 4
    url = "pubkey.asc"

# Menu links
[[menu.main]]
    name = "Projects"
    weight = 1
    url  = "/projects/"
[[menu.main]]
    name = "About"
    weight = 2
    url = "/about/"

[[deployment.targets]]
    name = "aws"
    URL = "s3://matusnovak.com?region=eu-west-1"
